import "./default-attributes-test.js";
import "./delete-test.js";
import "./find-test.js";
import "./insert-test.js";
import "./peek-test.js";
import "./serializer-embed-id-test.js";
import "./serializer-embed-uuid-test.js";
import "./reset-records-fixtures-test.js";
import "./update-test.js";
// import "./relationships/belongs-to-id-test.js";
// import "./relationships/belongs-to-uuid-test.js";
import "./relationships/has-one-id-test.js";
